#!/usr/bin/env php
<?php

require_once ('common/common.php');

$dayAndPart = explode('.', $_SERVER['argv'][1] ?? '');
if (!count($dayAndPart) == 2) {
    die("Pass argument as day.part, eg. 8.1\n");
}
$day = $dayAndPart[0];
$part = $dayAndPart[1];
$inputSuffix = $_SERVER['argv'][2] ?? null;
$dayPath = 'day-' . str_pad($day, 2, '0', STR_PAD_LEFT);
$inputFilename = __DIR__ . '/' . $dayPath . '/input' . ($inputSuffix ? '-' . $inputSuffix : '') . '.txt';

require_once $dayPath . '/day' . $day . '.php';

$className = 'Day' . $day;
/** @var AbstractSolution $solution */
$solution = new $className();
$startTime = microtime(true);
$result = $solution->solve($part, $inputFilename);
$endTime = microtime(true);

echo $result . "\n";
echo "\e[90mDuration: " . round($endTime - $startTime, 5) . " sec\n";
